name: Refresh Strava Credentials

on:
  schedule:
    - cron: '0 0 * * 0' # Chaque dimanche à minuit
  workflow_dispatch: {} # Déclenchement manuel

jobs:
  refresh-creds:
    runs-on: ubuntu-latest
    name: Refresh Strava Credentials
    steps:
      - uses: actions/checkout@v2 # Clone le dépôt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm install playwright
      
      - name: Fetch credentials
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
       run: |
          node ./scripts/refresh_strava_credential1.js

          # Supposons que le script écrit dans les variables d'environnement STRAVA_ID et STRAVA_COOKIES
          echo "::add-mask::${STRAVA_ID}"
          echo "::add-mask::${STRAVA_COOKIES}"
          echo "STRAVA_ID=${STRAVA_ID}" >> $GITHUB_ENV
          echo "STRAVA_COOKIES=${STRAVA_COOKIES}" >> $GITHUB_ENV

      - name: Write Strava creds to Cloudflare
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            STRAVA_ID
            STRAVA_COOKIES
