name: Refresh Strava Credentials

on:
  schedule:
    - cron: '0 0 * * 0'  # Exécution hebdomadaire chaque dimanche à minuit
  workflow_dispatch: {}  # Permet de déclencher manuellement

jobs:
  refresh-creds:
    runs-on: ubuntu-latest
    name: Refresh Strava Credentials
    steps:
      - uses: actions/checkout@v2  # Vérifie le code dans le dépôt
      - uses: denolib/setup-deno@v2  # Installe Deno
        with:
          deno-version: v1.x

      - name: Fetch credentials
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
        run: |
          # Exécutez le script Deno avec Playwright
          deno run --allow-net --allow-env --unstable ./scripts/refresh_strava_credentials1.ts

          # Supposons que le script écrit dans les variables d'environnement STRAVA_ID et STRAVA_COOKIES
          echo "::add-mask::${STRAVA_ID}"
          echo "::add-mask::${STRAVA_COOKIES}"
          echo "STRAVA_ID=${STRAVA_ID}" >> $GITHUB_ENV
          echo "STRAVA_COOKIES=${STRAVA_COOKIES}" >> $GITHUB_ENV

      - name: Write Strava creds to Cloudflare
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            STRAVA_ID
            STRAVA_COOKIES
